export * from "./type"
export * from "./validation"

export const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sImV4cCI6MTY5MjQ5NjMyMywidXNlcl9uYW1lIjoiZGV2ZWxvcEBnbWFpbC5jb20iLCJqdGkiOiJvYWoxOHpvLWlxQjJVcjFraTVLQm5RZFh2SGciLCJjbGllbnRfaWQiOiJteS1jbGllbnQtd2ViIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.pwCzpj-cZk3GYF5KVVD5TzGxl0oLR-ijV7rY0jHg3Vc"